### ISSUE TITLE
Some issue about the parameters

### ISSUE THREAD

**Issue by LinBornRain** [fairytale0011/Conditional-WassersteinGAN#2]
Hi fairytale0011:
It's glad to see ur interesting work about combining ACGAN and  WGAN!
Specifically,  I am curious about the parameters 1/2 in ' loss_c = (loss_c_r + loss_c_f) / 2' and the numbers of iteration as 1/5 as u mentioned and 'c_interv=2'.
Have u try some other parameters to balance the influence between CRITIC and CLASSIFIER to generator?
THX!

**Comment by fairytale0011** [comment]
The 1/2 in loss_c is just for averaging out the two CE loss (loss_c_r and loss_c_f).
Diters = 5 comes from the original WassersteinGAN paper ([https://arxiv.org/abs/1701.07875](https://arxiv.org/abs/1701.07875)).
For the 'c_interv=2' part, I remember it was a hack to make the training stable because the original WGAN has some serious problems because of its weight clipping. The [improved-WGAN](https://github.com/igul222/improved_wgan_training) is much better.

**Comment by LinBornRain** [comment]
Thanks for ur inspiration! I will check the papers to get more knowledge!
